name       : cgdb
version    : 0.7.1
release    : 1
source     :
    - https://github.com/cgdb/cgdb/archive/v0.7.1.tar.gz : eefbe5ca3e6bb03c1984c296d159296fa0693ea6573b1263948e8abe28dcabd4
license    : GPL-2.0-or-later
component  : programming.tools
summary    : Console front-end to the GNU debugger
description: |
    CGDB is a very lightweight console frontend to the GNU debugger. It provides a split screen interface showing the GDB session below and the program's source code above. The interface is modelled after vim's, so vim users should feel right at home using it.
setup      : |
    env CGDB_VERSION=0.7.1 ./autogen.sh
    %configure
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share
